# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: rcbpool

steps:
- script: |
    echo Simulating deployment...
    mkdir deployed
    echo Deployment successful!
  displayName: 'Simulate Deployment'

- script: |
    echo Contents of deployed folder:
    dir
  displayName: 'Verify Deployment Output'